version: '3.8'
services:
  db:
    container_name: mysql_container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
