version: '3.9'
services:
  db:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test_sample_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - ./data:/var/lib/mongodb/data